spring:
  task:
    execution:
      pool:
        core-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      read-only: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

springdoc:
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    path: /swagger-ui.html